version: 2.1
orbs:
  aws-cli: circleci/aws-cli@1.4.0

jobs:
  create_infrastructure:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup
      - run:
          name: Create Cloudformation Stack
          command: |
            aws cloudformation deploy \
              --template-file template.yml \
              --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5} \
              --region ${AWS_DEFAULT_REGION}
# Sequential workflow
workflows:
  my_aws_workflows:
    jobs:
      - create_infrastructure